Fix compilation with Python 3.13
Functions Py_SetProgramName and PySys_SetArgv were removed:

Python.xs: In function ‘do_pyinit’:
Python.xs:33:5: error: implicit declaration of function ‘Py_SetProgramName’; did you mean ‘Py_GetProgramName’? [-Werror=implicit-function-declaration]
   33 |     Py_SetProgramName(L"python");
      |     ^~~~~~~~~~~~~~~~~
      |     Py_GetProgramName
Python.xs:40:5: error: implicit declaration of function ‘PySys_SetArgv’ [-Werror=implicit-function-declaration]
   40 |     PySys_SetArgv(_python_argc, _python_argv);  /* Tk needs this */
      |     ^~~~~~~~~~~~~